-- Kurstabellen som POST /api/sync skriver til gjennom lib/db.ts.
-- Tabellen fantes fra før i produksjon, men manglet en migrasjon, så et nytt
-- Supabase-prosjekt satt opp etter README-en hadde ikke noe å skrive til.
-- Skjemaet her speiler den eksisterende tabellen. Alt er idempotent: på et
-- prosjekt som allerede har tabellen gjør create-setningen ingenting, og den
-- unike indeksen er den delen som faktisk kan mangle.
create table if not exists public.stock_prices (
  id bigint generated by default as identity primary key,
  symbol text not null,
  date date not null,
  open numeric not null,
  high numeric not null,
  low numeric not null,
  close numeric not null,
  adjusted_close numeric not null,
  volume bigint not null,
  change_pct numeric,
  prev_close numeric,
  avg_volume numeric,
  vol_ratio numeric,
  created_at timestamptz not null default now()
);

-- Uten denne feiler upserten i lib/db.ts med 42P10: onConflict "symbol,date"
-- blir til ON CONFLICT (symbol, date), som krever en unik indeks på kolonnene.
-- id-primærnøkkelen dekker ikke dette. Finnes det allerede duplikater av
-- samme symbol og dato, stopper denne setningen med en tydelig feil; rydd
-- dem da bort først, slik at én dato per aksje står igjen.
create unique index if not exists stock_prices_symbol_date
  on public.stock_prices (symbol, date);

-- Samme tilgangsmodell som nyhetstabellene: bare service role slipper til.
-- Appen leser aldri denne tabellen, så dette bryter ingen eksisterende visning.
alter table public.stock_prices enable row level security;
revoke all on public.stock_prices from anon, authenticated;
grant all on public.stock_prices to service_role;
